<?php
/**
 * Created by PhpStorm.
 * User: flame
 * Date: 14-12-16
 * Time: 上午9:50
 */

return array(
    'di'=>array(
           'MicroHome\Model\CommentTable'=>'MicroHome\Model\CommentTable',
           'MicroHome\Model\ImgTable'=>'MicroHome\Model\ImgTable',
           'MicroHome\Model\InfoTable'=>'MicroHome\Model\InfoTable',
           'MicroHome\Model\ScrutinyTable'=>'MicroHome\Model\ScrutinyTable',
           'MicroHome\Model\UserTable'=>'MicroHome\Model\UserTable',
           'MicroHome\Model\PraiseTable'=>'MicroHome\Model\PraiseTable',
    ),
    'router'=>array(
        'routes'=>array(
            'microhome_show_all'=>array(
                'type'=>'Segment',
                'options'=>array(
                    'route'=>'/api/shujuxia_microhome_show/all',
                    'defaults'=>array(
                        'controller'=>'MicroHome\Controller\ShowPageController'
                    )
                ),
            ),
            'microhome_show_one'=>array(
                'type'=>'Segment',
                'options'=>array(
                    'route'=>'/api/shujuxia_microhome_show/one/:id',
                    'constraints'=>array(
                        'id'=>'\w+'
                    ),
                    'defaults'=>array(
                        'controller'=>'MicroHome\Controller\ShowPageController'
                    )
                ),
            ),

            'microhome_showMy'=>array(
                'type'=>'Segment',
                'options'=>array(
                    'route'=>'/api/shujuxia_microhome_showMy[/:id]',
                    'constraints'=>array(
                        'id'=>'\w+'
                    ),
                    'defaults'=>array(
                        'controller'=>'MicroHome\Controller\ShowMyPageController'
                    )
                ),
            ),
            'microhome_praise'=>array(
                'type'=>'Literal',
                'options'=>array(
                    'route'=>'/api/shujuxia_microhome_praise',
                    'defaults'=>array(
                        'controller'=>'MicroHome\Controller\PraiseController'
                    )
                ),
            ),
            'microhome_sendinfo'=>array(
                'type'=>'Literal',
                'options'=>array(
                    'route'=>'/api/shujuxia_microhome_sendinfo',
                    'defaults'=>array(
                        'controller'=>'MicroHome\Controller\SendInfoController'
                    )
                ),
            ),
            'microhome_sendcomment'=>array(
                'type'=>'Literal',
                'options'=>array(
                    'route'=>'/api/shujuxia_microhome_sendcomment',
                    'defaults'=>array(
                        'controller'=>'MicroHome\Controller\SendCommentController'
                    ),
                ),
            ),
            'microhome_delinfo'=>array(
                'type'=>'Segment',
                'options'=>array(
                    'route'=>'/api/shujuxia_microhome_delinfo/:id',
                    'defaults'=>array(
                        'controller'=>'MicroHome\Controller\DeleteInfoController'
                    ),
                ),
            ),
            'microhome_backstage_scrutiny'=>array(
                'type'=>'Literal',
                'options'=>array(
                    'route'=>'/api/shujuxia_microhome_backstage_scrutiny',
                    'defaults'=>array(
                        'controller'=>'MicroHome\Controller\BackStageScrutinyController'
                    )
                ),
            ),
            'microhome_backstage_show'=>array(
                'type'=>'Segment',
                'options'=>array(
                    'route'=>'/api/shujuxia_microhome_backstage_show[/:id]',
                    'defaults'=>array(
                        'controller'=>'MicroHome\Controller\BackStageShowController'
                    )
                ),
            ),
            'microhome_getconditioninfo'=>array(
                'type'=>'Segment',
                'options'=>array(
                    'route'=>'/api/shujuxia_microhome_getcondition',
//                    'constraints'=>array(
//                        'id'=>'\w+',
//                        'num'=>'\w+'
//                    ),
                    'defaults'=>array(
                        'controller'=>'MicroHome\Controller\GetConditionInfoController'
                    )
                ),
            ),
            'microhome_user'=>array(
                'type'=>'Segment',
                'options'=>array(
                    'route'=>'api/shujuxia_microhome_user',
                    'defaults'=>array(
                        'controller'=>'MicroHome\Controller\UserController'
                    ),
                ),
            ),
        ),
    ),

    'controllers'=>array(
        'invokables'=>array(
            'MicroHome\Controller\BackStageScrutinyController'=>'MicroHome\Controller\BackStageScrutinyController',
            'MicroHome\Controller\BackStageShowController'=>'MicroHome\Controller\BackStageShowController',
            'MicroHome\Controller\ShowPageController'=>'MicroHome\Controller\ShowPageController',
            'MicroHome\Controller\ShowMyPageController'=>'MicroHome\Controller\ShowMyPageController',
            'MicroHome\Controller\PraiseController'=>'MicroHome\Controller\PraiseController',
            'MicroHome\Controller\SendInfoController'=>'MicroHome\Controller\SendInfoController',
            'MicroHome\Controller\SendCommentController'=>'MicroHome\Controller\SendCommentController',
            'MicroHome\Controller\DeleteInfoController'=>'MicroHome\Controller\DeleteInfoController',
            'MicroHome\Controller\GetConditionInfoController'=>'MicroHome\Controller\GetConditionInfoController',
            'MicroHome\Controller\SelectPageController'=>'MicroHome\Controller\SelectPageController',
            'MicroHome\Controller\UserController'=>'MicroHome\Controller\UserController',

        ),
    ),
);